//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generated\FrwTwemoji\Properties\AssemblyInfo.cs.
        /// </summary>
        internal static string File_FrwTwemoji_AssemblyInfo_cs {
            get {
                return ResourceManager.GetString("File_FrwTwemoji_AssemblyInfo_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generated\FrwTwemoji\FrwTwemoji.csproj.
        /// </summary>
        internal static string File_FrwTwemoji_csproj {
            get {
                return ResourceManager.GetString("File_FrwTwemoji_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generated\FrwTwemoji\RegEx.cs.
        /// </summary>
        internal static string File_FrwTwemoji_RegEx_cs {
            get {
                return ResourceManager.GetString("File_FrwTwemoji_RegEx_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generated\FrwTwemoji{0}\FrwTwemoji{0}.csproj.
        /// </summary>
        internal static string File_FrwTwemojiXXX_csproj {
            get {
                return ResourceManager.GetString("File_FrwTwemojiXXX_csproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EmojiSources.txt.
        /// </summary>
        internal static string FileEmojiSources {
            get {
                return ResourceManager.GetString("FileEmojiSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generated\PreviousAssetsBackup.xml.
        /// </summary>
        internal static string FilePreviousAssetsBackup {
            get {
                return ResourceManager.GetString("FilePreviousAssetsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StandardizedVariants.txt.
        /// </summary>
        internal static string FileStandardizedVariants {
            get {
                return ResourceManager.GetString("FileStandardizedVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitter-twemoji\2\.
        /// </summary>
        internal static string FolderTwitterTwemoji {
            get {
                return ResourceManager.GetString("FolderTwitterTwemoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.unicode.org/Public/UNIDATA/EmojiSources.txt.
        /// </summary>
        internal static string UrlEmojiSources {
            get {
                return ResourceManager.GetString("UrlEmojiSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.unicode.org/Public/UNIDATA/StandardizedVariants.txt.
        /// </summary>
        internal static string UrlStandardizedVariants {
            get {
                return ResourceManager.GetString("UrlStandardizedVariants", resourceCulture);
            }
        }
    }
}
