//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyzing all assets ....
        /// </summary>
        internal static string AssetCollection_AnalizeAllAsset_Analyzing_all_assets {
            get {
                return ResourceManager.GetString("AssetCollection_AnalizeAllAsset_Analyzing_all_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [INFO] asset {0} contains {1} emoji.
        /// </summary>
        internal static string AssetCollection_AnalizeAllAsset_INFO_asset_X_contains_X_emoji {
            get {
                return ResourceManager.GetString("AssetCollection_AnalizeAllAsset_INFO_asset_X_contains_X_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à analizing EmojiSources VS our assets ... .
        /// </summary>
        internal static string Program_DoRebuild_analizing_EmojiSources_VS_our_assets {
            get {
                return ResourceManager.GetString("Program_DoRebuild_analizing_EmojiSources_VS_our_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à analizing StandardizedVariants VS our assets ... .
        /// </summary>
        internal static string Program_DoRebuild_analizing_StandardizedVariants_VS_our_assets {
            get {
                return ResourceManager.GetString("Program_DoRebuild_analizing_StandardizedVariants_VS_our_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fetching EmojiSources.txt ... .
        /// </summary>
        internal static string Program_DoRebuild_fetching_EmojiSources_txt {
            get {
                return ResourceManager.GetString("Program_DoRebuild_fetching_EmojiSources_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fetching StandardizedVariants.txt ... .
        /// </summary>
        internal static string Program_DoRebuild_fetching_StandardizedVariants_txt {
            get {
                return ResourceManager.GetString("Program_DoRebuild_fetching_StandardizedVariants_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [INFO] parsed {0} standard emoji..
        /// </summary>
        internal static string Program_DoRebuild_INFO_parsed_0_standard_emoji {
            get {
                return ResourceManager.GetString("Program_DoRebuild_INFO_parsed_0_standard_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [INFO] parsed {0} variant sensitive emoji..
        /// </summary>
        internal static string Program_DoRebuild_INFO_parsed_X_variant_sensitive_emoji {
            get {
                return ResourceManager.GetString("Program_DoRebuild_INFO_parsed_X_variant_sensitive_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [WARNING] missing emoji for assets {0}:{1}.
        /// </summary>
        internal static string Program_DoRebuild_WARNING_missing_emoji_for_assets_X_X {
            get {
                return ResourceManager.GetString("Program_DoRebuild_WARNING_missing_emoji_for_assets_X:X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press a key to end.
        /// </summary>
        internal static string Program_Main_Press_a_key_to_end {
            get {
                return ResourceManager.GetString("Program_Main_Press_a_key_to_end", resourceCulture);
            }
        }
    }
}
