//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // --------------------------------------------------------------------------------------------------------------------
        ///// &lt;copyright file=&quot;AssemblyInfo.cs&quot; company=&quot;FrenchW.net from @FrenchW&quot;&gt;
        /////   Copyright FrenchW © 2014-2016.
        /////   FrwTwemoji Project page : http://github.frenchw.net/FrwTwemoji/
        /////   This software is licenced like https://github.com/twitter/twemoji :
        /////   Code licensed under the MIT License: http://opensource.org/licenses/MIT
        /////   Graphics licensed under CC-BY 4.0: https://creativec [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Twemoji_assembly_nfo_start {
            get {
                return ResourceManager.GetString("Twemoji_assembly_nfo_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;/Project&gt;.
        /// </summary>
        internal static string Twemoji_csproj_end {
            get {
                return ResourceManager.GetString("Twemoji_csproj_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup Condition=&quot; &apos;$(Configuration)|$(Platform)&apos; == &apos;Release|AnyCPU&apos; &quot;&gt;
        ///    &lt;DebugType&gt;pdbonly&lt;/DebugType&gt;
        ///    &lt;Optimize&gt;true&lt;/Optimize&gt;
        ///    &lt;OutputPath&gt;..\ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Twemoji_csproj_start {
            get {
                return ResourceManager.GetString("Twemoji_csproj_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à \\uD83D[\\uDC68-\\uDC69](?:\\uD83C[\\uDFFB-\\uDFFF])?\\u200D(?:\\u2695\\uFE0F|\\u2696\\uFE0F|\\u2708\\uFE0F|\\uD83C[\\uDF3E\\uDF73\\uDF93\\uDFA4\\uDFA8\\uDFEB\\uDFED]|\\uD83D[\\uDCBB\\uDCBC\\uDD27\\uDD2C\\uDE80\\uDE92])|(?:\\uD83C[\\uDFCB\\uDFCC]|\\uD83D\\uDD75|\\u26F9)(?:\\uFE0F|\\uD83C[\\uDFFB-\\uDFFF])\\u200D[\\u2640\\u2642]\\uFE0F|(?:\\uD83C[\\uDFC3\\uDFC4\\uDFCA]|\\uD83D[\\uDC6E\\uDC71\\uDC73\\uDC77\\uDC81\\uDC82\\uDC86\\uDC87\\uDE45-\\uDE47\\uDE4B\\uDE4D\\uDE4E\\uDEA3\\uDEB4-\\uDEB6]|\\uD83E[\\uDD26\\ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Twemoji_RegEx {
            get {
                return ResourceManager.GetString("Twemoji_RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à     }
        ///}.
        /// </summary>
        internal static string Twemoji_RegEx_cs_end {
            get {
                return ResourceManager.GetString("Twemoji_RegEx_cs_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // --------------------------------------------------------------------------------------------------------------------
        ///// &lt;copyright file=&quot;RegEx.cs&quot; company=&quot;FrenchW.net from @FrenchW&quot;&gt;
        /////   Copyright FrenchW © 2014-2016.
        /////   FrwTwemoji Project page : http://github.frenchw.net/FrwTwemoji/
        /////   This software is licenced like https://github.com/twitter/twemoji :
        /////   Code licensed under the MIT License: http://opensource.org/licenses/MIT
        /////   Graphics licensed under CC-BY 4.0: https://creativecommons. [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Twemoji_RegEx_cs_start {
            get {
                return ResourceManager.GetString("Twemoji_RegEx_cs_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup Condition=&quot; &apos;$(Configuration)|$(Platform)&apos; == &apos;Release|AnyCPU&apos; &quot;&gt;
        ///    &lt;DebugType&gt;pdbonly&lt;/DebugType&gt;
        ///    &lt;Optimize&gt;true&lt;/Optimize&gt;
        ///    &lt;OutputPath&gt;..\ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TwemojiXXX_csproj_start {
            get {
                return ResourceManager.GetString("TwemojiXXX_csproj_start", resourceCulture);
            }
        }
    }
}
